import type { Config } from 'tailwindcss'

export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{vue,ts}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-container-high': '#222a3d',
        'on-tertiary-container': '#3e2b00',
        'inverse-on-surface': '#283044',
        'error-container': '#93000a',
        'primary-container': '#818cf8',
        'on-error': '#690005',
        'surface-container-highest': '#2d3449',
        'surface-container-lowest': '#060e20',
        'surface-dim': '#0b1326',
        'on-primary-fixed-variant': '#2f3aa3',
        'error': '#ffb4ab',
        'on-primary-container': '#101b8a',
        'outline': '#908f9e',
        'on-tertiary-fixed-variant': '#5d4200',
        'primary-fixed-dim': '#bdc2ff',
        'surface-container': '#171f33',
        'surface-bright': '#31394d',
        'primary-fixed': '#e0e0ff',
        'on-secondary-fixed-variant': '#2f2ebe',
        'on-secondary-fixed': '#07006c',
        'secondary-fixed': '#e1e0ff',
        'on-background': '#dae2fd',
        'secondary-fixed-dim': '#c0c1ff',
        'on-primary': '#131e8c',
        'on-tertiary-fixed': '#261900',
        'outline-variant': '#454653',
        'on-secondary-container': '#b0b2ff',
        'surface-tint': '#bdc2ff',
        'on-primary-fixed': '#000767',
        'primary': '#bdc2ff',
        'on-secondary': '#1000a9',
        'tertiary-fixed': '#ffdea3',
        'surface-container-low': '#131b2e',
        'surface': '#0b1326',
        'on-tertiary': '#402d00',
        'tertiary-fixed-dim': '#f7bd3e',
        'inverse-primary': '#4953bc',
        'secondary': '#c0c1ff',
        'on-surface': '#dae2fd',
        'surface-variant': '#2d3449',
        'background': '#0b1326',
        'secondary-container': '#3131c0',
        'on-error-container': '#ffdad6',
        'tertiary': '#f7bd3e',
        'on-surface-variant': '#c6c5d5',
        'inverse-surface': '#dae2fd',
        'tertiary-container': '#c08d00',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        margin: '24px',
        gutter: '16px',
        unit: '4px',
        'stack-md': '16px',
        'stack-sm': '8px',
        'container-max': '1440px',
        'stack-lg': '32px',
      },
      fontFamily: {
        'label-caps': ['Inter'],
        'headline-sm': ['Inter'],
        'body-sm': ['Inter'],
        'body-md': ['Inter'],
        'label-code': ['JetBrains Mono'],
        'body-lg': ['Inter'],
        'headline-md': ['Inter'],
        'headline-lg': ['Inter'],
      },
      fontSize: {
        'label-caps': ['11px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '700' }],
        'headline-sm': ['18px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-sm': ['12px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-code': ['13px', { lineHeight: '1.4', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
} satisfies Config
